name: FirstFlow
on: 
    push: 
        branches: ["develop","main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting
              run: echo "Hi"
            - name: Ckeckout
              uses: actions/checkout@v4
            - name: Listing workspace
              run: ls -latr
