name: FirstFlow
on: 
    push: 
        branches: ["develop","main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting
              run: echo "Hi"
            - name: Listing dir
              run: ls -latr
